[versions]
kotlin = "2.3.10"
kotlinx-html = "0.12.0"
kaml = "0.104.0"

[libraries]
kotlinx-html-jvm = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version.ref = "kotlinx-html" }
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
